#!/bin/bash

x=${1/.tex/.xml}
b=${1/.tex/}

latexml $1 > $x
latexmlpost --format=html5 \
   --javascript='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js' \
   --destination="outdir/${b}.html" $x

