#!/bin/bash
# set -e
export PATH=/usr/local/texlive/2020/bin/x86_64-linux:$PATH

rm -f document.log
/usr/bin/timeout --kill-after=2s 15s $1 $2 > /dev/null
R=$?
echo -e "\nTimeout/Error status: $R"  >> document.log
exit $R
