#!/usr/bin/perl

use CGI;
use File::Path ('remove_tree');
use File::Copy;


my $cgi = new CGI;
 my($tmpdir,$return);
 $tmpdir="/tmp/showtags-$$";
 mkdir($tmpdir, 0777) unless (-d $tmpdir);

 my $name = "document.pdf";
 my $download = $cgi->param('download');

 my $pdfdoc = $cgi->param('pdfdoc');
 my $file = $cgi->param('pdffile');
 
 my $maxdepth = $cgi->param('maxdepth');
 my $maxsiblings = $cgi->param('maxsiblings');
 my $RootElem = $cgi->param('RootElem');
 my $RootElemOcc = $cgi->param('RootElemOcc');
 my $ElideElem = $cgi->param('ElideElem');
 my $OmitAtts = $cgi->param('OmitAtts');
 my $maxattlength = $cgi->param('maxattlength');
 my $ShowEmptyAtts = $cgi->param('ShowEmptyAtts');
 my $NameStyle  = $cgi->param('NameStyle');
 my $MaxStringLength  = $cgi->param('MaxStringLength');
 my $nsPrefix  = $cgi->param('nsPrefix');
 my $nsURI  = $cgi->param('nsURI');

 if (-e "/var/www/html/latexcgi/" . $pdfdoc . ".pdf") {
     copy("/var/www/html/latexcgi/" . $pdfdoc . ".pdf", $tmpdir . "/$name");
     $file=$pdfdoc;
} elsif (-e "/var/www/html/demo/" . $pdfdoc . ".pdf") {
    copy("/var/www/html/demo/" . $pdfdoc . ".pdf", $tmpdir . "/$name");
    $file=$pdfdoc;
} else {
    open(LOCAL, ">$tmpdir/$name") or print 'error';
    my $file_handle = $cgi->upload('pdffile'); 
    while(<$file_handle>) {    
	print LOCAL $_;
    }
 close($file_handle);                  
 close(LOCAL);
 }

print $cgi->header( 
	-type    => 'text/html',
	-charset => 'charset=UTF-8');


print <<EOT;
<!DOCTYPE html>
<html>
  <head>
    <title>Tag Tree Diagrams: $file</title>
    <meta charset="UTF-8"/>
    <style>
     body {margin-left:2em}
    .element {color: darkred;font-weight: bold;}
    .attribute {color: black;font-weight: bold;}
    .comment {color: black;font-weight: bold;font-style: italic;background-color:beige;}
    .attval {color: blue}
    .procinst {color: darkgreen;font-weight: bold;}
    span.adoc {background-color: #DDD;}
    span.md {background-color: #EEE;}

#showsettings {
border: solid thin black;
border-radius:1em;
padding:1em;
}
#val, #puml {
border: solid thin black;
border-radius:1em;
padding:1em;
}

pre {
border: solid thin black;
border-radius:1em;
padding:1em;
white-space: pre-wrap;
}
    </style>
<script>
function  simpleuml() {
const p = document.getElementById("plantumlpre");
let t = p.textContent;
t=t.replace(/^[^!]*T[!]/,"[tagtree]\\n....").replaceAll(/[*][*]/g,'');
p.textContent=t;
}
</script>
  </head>
  <body>
<h1>PlantUML Structure Tree Diagrams</h1>

<div><button type="button" onclick="history.back()">Return to the plantuml form</button><br></div>

<h2 id="set">Settings</h2>

<div id="showsettings">
EOT
print "File uploaded: <b>$file</b><br>\n";

print <<EOT;
</div>


<h2 id="plantuml">Open at PlantUML.com</h2>
<div id="puml">
<a target="_blank" href="https://editor.plantuml.com/uml/
EOT

my $pumlcode=0;
my $xslopts="";
if ($maxdepth =~ /^[0-9]+$/) {$xslopts=$xslopts . " maxdepth=$maxdepth";}
if ($maxsiblings =~ /^[0-9]+$/) {$xslopts=$xslopts . " maxsiblings=$maxsiblings";}
if ($RootElemOcc =~ /^[0-9]+$/) {$xslopts=$xslopts . " occurrence=$RootElemOcc";}
if ($RootElem =~ /^[a-zA-Z0-9]+$/) {$xslopts=$xslopts . " rootelem=$RootElem";}
if ($ElideElem =~ /^[a-zA-Z0-9 ,]+$/) {$xslopts=$xslopts . " elidecontent='$ElideElem'";}
if ($OmitAtts =~ /^[a-zA-Z0-9 ,]+$/) {$xslopts=$xslopts . " omitatts='$OmitAtts'";}
if ($maxattlength =~ /^[0-9]+$/) {$xslopts=$xslopts . " maxattlength=$maxattlength";}
if ($ShowEmptyAtts eq "on") {$xslopts=$xslopts . " showemptyatts=yes";}
if ($NameStyle =~ /^[0-9]+$/) {$xslopts=$xslopts . " namestyle=$NameStyle";}
if ($MaxStringLength =~ /^[0-9]+$/) {$xslopts=$xslopts . " maxstringlength=$MaxStringLength";}
if ($nsPrefix =~ /^[^';<>"]+$/) {$xslopts=$xslopts . " nsprefix='$nsPrefix'";}
if ($nsURI =~ /^[^';<>"]+$/) {$xslopts=$xslopts . " nsuri='$nsURI'";}


chdir($tmpdir);
    $ENV{'LUAINPUTS'}="/home/david/show-pdf-tags/:";
    $ENV{'PATH'}="/usr/local/texlive/2026/bin/x86_64-linux:" . $ENV{'PATH'};

my $scode=0;
my $pumlcode=0;

$scode =  system("texlua /home/david/show-pdf-tags/show-pdf-tags.lua --xml --map $name > document.xml");

$pumlcode=system("java -jar ~david/jars/Saxon-HE-10.9.jar document.xml ~david/plantuml2.xsl $xslopts 2>/dev/null > /dev/null ");
my $pumlcode2=0;
$pumlcode=system("java -jar ~david/jars/plantuml-1.2025.10.jar -encodeurl document.puml 2>/dev/null");

print <<EOT;
">Open at plantuml.com in a new tab</a>
</div>


<h2 id="ns">Namespace Table</h2>

<pre id="nspre">
EOT
system("sed -e 's/</&lt;/g' document-ns.txt");
print <<EOT;
</pre>

<h2>Table Layout</h2>
(Showing header markup for both Asciidoc and Markdown, delete one.)
<pre>
EOT
system("sed -e 's/</&lt;/g' -e 's/span class=/<span class=/' -e 's:/span:</span:' document-table.txt");
print <<EOT;
</pre>


<h2>PlantUML Layout</h2>
<button type="button" onclick="simpleuml()">simplify uml</button>
<pre id="plantumlpre">
EOT
system("sed -e 's/</&lt;/g' document.puml");
print <<EOT;
</pre>


</body>
</html>
EOT
        chdir("..");
        remove_tree($tmpdir);
