#!/bin/bash
# set -e
export PATH=/usr/local/texlive/2020/bin/x86_64-linux:$PATH

echo "" >  document.log

NS=""
REC=""
MT=""

if [ "X$1X" == "XlualatexX" ]; then
    NS="--nosocket"
fi

if [ "X$1X" == "Xmake4htX" ]; then
    NS="-d outdir"
    MT=2,mathjax
fi

case "X$1" in
    Xbibtex)
    REC=""
    ;;
    *tex)
    REC="--recorder"
    ;;
    *latex-dev)
    REC="--recorder"
    ;;
esac

# $2 may contain spaces so multiple arguments eg for makeindex
# calling script checks no shell characters
/usr/bin/timeout --kill-after=2s 15s $1 $NS $REC $2 $MT > /dev/null 2> /dev/null
R=$?

# allow /usr /tmp and /etc/fonts and /dev/null
if [ "X$REC" == "X--recorder" ]; then
    if grep -q 'INPUT /[^utd]...[^fn]' ${2}.fls; then
 R=1
 echo "Bad Input" > document.log
    fi
fi

echo -e "\nTimeout/Error status: $R [$1][$2]"  >> document.log
exit $R
