#!/bin/bash
# set -e
export PATH=/usr/local/texlive/2020/bin/x86_64-linux:$PATH

echo "" >  document.log

NS=""
REC=""

if [ "X$1X" == "XlualatexX" ]; then
    NS="--nosocket"
fi
case "X$1" in
    *latex)
    REC="--recorder"
    ;;
esac

# $2 may contain spaces so multiple arguments eg for makeindex
# calling script checks no shell characters
/usr/bin/timeout --kill-after=2s 15s $1 $NS $REC $2 > /dev/null 2> /dev/null
R=$?

# allow /usr /tmp and /etc/fonts
if [ "X$REC" == "X--recorder" ]; then
    if grep -q 'INPUT /[^utd]...[^fn]' ${2}.fls; then
 R=1
 echo "Bad Input" > document.log
    fi
fi

echo -e "\nTimeout/Error status: $R"  >> document.log
exit $R
