#!/bin/bash
# set -e
export PATH=/usr/local/texlive/2021/bin/x86_64-linux:$PATH

echo "" >  document.log

NS=""
REC=""
MT=""
ENG="$1"

if [ "X$1X" == "XlualatexX" ]; then
    NS="--nosocket"
fi

if [ "X$1X" == "XxetexX" ] || [ "X$1X" == "XxelatexX" ] ; then
  ENG="$1-unsafe"
fi


if [ "X$1X" == "Xmake4htX" ]; then
#    NS="-d outdir -a debug"
    NS="-d outdir"
    MT=learnlatex4ht,2,mathml,mathjax,svg
    cp /usr/local/texlive/texmf-local/tex/generic/tex4ht/learnlatex4ht.cfg .
fi

case "X$1" in
    Xlatexcgilwarp*)
    REC=""
    ;;
    Xbibtex)
    REC=""
    ;;
    *tex)
    REC="--recorder"
    ;;
    *latex-dev)
    REC="--recorder"
    ;;
esac

# $2 may contain spaces so multiple arguments eg for makeindex
# calling script checks no shell characters
# /usr/bin/timeout --kill-after=2s 15s $1 $NS $REC $2 $MT  >> document.log 2> document.err
/usr/bin/timeout --kill-after=2s 15s $ENG $NS $REC $2 $MT > /dev/null 2> /dev/null
R=$?

# allow /usr /tmp and /etc/fonts and /dev/null
if [ "X$REC" == "X--recorder" ]; then
    if grep -q 'INPUT /[^utd]...[^fn]' ${2}.fls; then
 R=1
 echo "Bad Input" > document.log
    fi
fi

echo -e "\nTimeout/Error status: $R [$1][$2]"  >> document.log

# cat document.err >> document.log

exit $R
