#!/usr/bin/perl

use CGI;
use File::Path ('remove_tree');
use File::Copy;


my $cgi = new CGI;
 my($tmpdir,$return);
 $tmpdir="/tmp/showtags-$$";
 mkdir($tmpdir, 0777) unless (-d $tmpdir);

 my $name = "document.pdf";
 my $download = $cgi->param('download');
 my $followmap = $cgi->param('followmap');
 my $schema = $cgi->param('schema');
 my $pdfdoc = $cgi->param('pdfdoc');
 my $file = $cgi->param('pdffile');
 
 if (-e "/var/www/html/latexcgi/" . $pdfdoc . ".pdf") {
     copy("/var/www/html/latexcgi/" . $pdfdoc . ".pdf", $tmpdir . "/$name");
     $file=$pdfdoc;
 } else {
  open(LOCAL, ">$tmpdir/$name") or print 'error';
  my $file_handle = $cgi->upload('pdffile'); 
 while(<$file_handle>) {    
    print LOCAL $_;
 }
 close($file_handle);                  
 close(LOCAL);
 }

if ($download eq "on" ) {
    print $cgi->header( 
	-type    => 'application/x-download',
	Content_disposition => 'attachment; filename=document.xml',
	-charset => 'charset=UTF-8',
	);
} else {
    print $cgi->header( 
	-type    => 'text/xml',
	-charset => 'charset=UTF-8');
}

print "<!--\n";
print "$file has been successfully uploaded\n";
print "follow map: $followmap, schema: $schema\n";
 print "-->\n";
     chdir($tmpdir);
    $ENV{'PATH'}="/usr/local/texlive/2024/bin/x86_64-linux:" . $ENV{'PATH'};

my $mapopt="";
if ($followmap eq "on" ) {
    $mapopt = "--map";
}

my $scode=0;

$scode =  system("texlua /home/david/show_pdf_tags/show_pdf_tags.lua --xml $mapopt $name > document.xml");

if($schema ne "none") {
 print "<!--\nRNV validation\n\n";
 system("/home/david/rnv \"/home/david/rnc/$schema.rnc\" document.xml 2>&1");
 print "\n-->\n";
}


if ($scode!=0) {
print "\n<error><![CDATA[\n";
}
system("sed -e 's/www.w3.org/-www.w3.org/g' document.xml");
if ($scode!=0) {
print "\n]]></error>\n";
}

        chdir("..");
        remove_tree($tmpdir);
